server:
  port: 9080
spring:
  influxdb:
    url: http://localhost:8086
    username: admin
    password:
    database: wyl
    retention-policy: autogen
    connect-timeout: 10
    read-timeout: 30
    write-timeout: 10
    gzip: true
